#baseurl = "C:/Users/zhe00a/Documents/Working/04-Software/044-WebPhenoCopter/PhenoCopterCS/Phenocopter/wwwroot/help"
#baseurl = "https://phenocopter.csiro.au/help"
baseurl = "https://localhost:44308/help"
languageCode = "en-us"
DefaultContentLanguage = "en"

title = "PhenoCopter Documentation"
theme = "hugo-theme-docdock"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
uglyurls = true
publishDir = "../PhenoCopterCS/Phenocopter/wwwroot/help"
[params]

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "Home"
identifier = "hugodoc"
url = "../"
weight = 2

